### ISSUE TITLE
Are providers applications?

### ISSUE THREAD

**Issue by madofo** [jlivingood/IETF-L4S-Deployment#11]
I was confused between §4.1 Only Applications Mark Traffic and §4.2 All Providers Welcome.

If only applications mark traffic, then who/what are the providers marking traffic based on guidance in §4.2? Are these application providers? If they're other network operators maybe it would be clearer to say something like:

`'Any network provider should be able to distribute traffic marked for the low-latency queue of another provider with no restrictions other than standards compliance or other reasonable and openly documented technical guidelines.'`

**Comment by jlivingood** [comment]
Ack - will address in next revision

**Comment by jlivingood** [comment]
https://github.com/jlivingood/IETF-L4S-Deployment/pull/19
