### ISSUE TITLE
Is low-latency networking a cable network specific technology?

### ISSUE THREAD

**Issue by madofo** [jlivingood/IETF-L4S-Deployment#12]
Is there something cable network specific about L4S? I had always assumed that is not the case. To make this document more generally applicable, would it hurt to s/cable modem/customer premises equipment/g ?

**Comment by jlivingood** [comment]
Ack - will address in next revision
(and L4S is not cable-specific so will clarify as well)

**Comment by jlivingood** [comment]
https://github.com/jlivingood/IETF-L4S-Deployment/pull/20

**Comment by jlivingood** [comment]
Also copied over current state from local XML source
