### ISSUE TITLE
Switch marking ECT1 vs congestion response ordering

### ISSUE THREAD

**Issue by goelvidhi** [jlivingood/IETF-L4S-Deployment#43]
I think it'd be good to switch the ordering between marking ECT1 vs responding to congestion marking. Because, someone could read marking first and implement that as it is quite easy and then look at congestion response and ignore that if it seems too complicated.

When someone reads this, they should get the essence that they MUST implement congestion response before setting ECT1 on their packets.

**Comment by jlivingood** [comment]
Addressing soon in a -03 version of ID
