### ISSUE TITLE
Recommend users run CableLabs L4S App several (many) times 

### ISSUE THREAD

**Issue by gwhiteCL** [jlivingood/IETF-L4S-Deployment#59]
In Week5-PartA.md, I'd suggest asking users to run the app several times in order to gather better data.  This is for a couple reasons:

- Results from any test run will be impacted by other traffic that may be present on the user's network or on the link between Comcast and the CL server.
- The CL server will only accept a single test at a time. If two users happen to collide, one of them will not actually produce any data (and this is not obvious to the user). Running the test a few times will increase the likelihood that we get useful data.

**Comment by jlivingood** [comment]
https://github.com/jlivingood/IETF-L4S-Deployment/pull/60
